image: ubuntu-latest

stages:
  - build

build:
  stage: build
  script:
    - uses: actions/checkout@v2
    - name: Check codestyle
      run: git ls-files *.{c,h} | xargs clang-format -i && git diff --exit-code
    - name: Build application
      run: make
